### ISSUE TITLE
remove the need to connect to see/blocking wallets

### ISSUE THREAD

**Issue by emudoteth** [Naim-Bijapure/multisig-se2#12]
![telegram-cloud-photo-size-1-5165830657987947480-y](https://github.com/Naim-Bijapure/multisig-se2/assets/27504011/ed368753-dc5c-4818-8e10-793b4e68b76b)

lets try to get this so that anyone can see the info and isnt forced to log in/switch networks until they need to.

crushing it as always fren!

**Comment by Naim-Bijapure** [comment]
i think without connecting correct wallet we cant fetch the required wallet info
