### ISSUE TITLE
split eth `comma separated address list` only allows one name to resolve, forcing to copy paste a list from elsewhere

### ISSUE THREAD

**Issue by emudoteth** [Naim-Bijapure/multisig-se2#5]
![image](https://github.com/Naim-Bijapure/multisig-se2/assets/27504011/70069c3d-d15d-4a54-9e6f-fdb50ff3c53e)

when attempting to write in more than one address or ens, the field becomes dead after one address resolves. forces users to copy and paste a list that they have to make elsewhere. 

this should allow users to write in addresses and ens in many formats. comma, comma space, type and hit enter, etc. 

maybe more like this and if the amounts are equal there is a little radio button at the top that makes them all the same? 
![image](https://github.com/Naim-Bijapure/multisig-se2/assets/27504011/d3d87e9e-578e-4a4e-afb9-ffd992ad5e26)

**Comment by Naim-Bijapure** [comment]
added some delay on input , it will solve this issue.
